"""inital setup

Revision ID: bdeb27d7abf4
Revises: 
Create Date: 2026-08-31 12:29:11.908554

"""
from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision = 'bdeb27d7abf4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certification_schemes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scheme_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('certification_type', sa.String(length=100), nullable=True),
    sa.Column('mandatory', sa.String(length=255), nullable=True),
    sa.Column('authority', sa.String(length=150), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laboratories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lab_code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('contact_person', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('validity_date', sa.Date(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('service_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('eligibility', sa.Text(), nullable=True),
    sa.Column('documents_required', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('standards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_number', sa.String(length=100), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('technical_department', sa.String(length=150), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('document_url', sa.Text(), nullable=True),
    sa.Column('last_verified_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('is_number')
    )
    op.create_table('uploads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('upload_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.Enum('PARAGRAPH', 'HEADING', 'TABLE', 'OCR', 'CODE', 'LIST', 'TRANSCRIPT', 'DESCRIPTION', name='documentblocktype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_standard_mapping',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('standard_id', sa.Integer(), nullable=False),
    sa.Column('relevance', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('standard_amendments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('standard_id', sa.Integer(), nullable=False),
    sa.Column('amendment_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('document_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('standard_certification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('standard_id', sa.Integer(), nullable=False),
    sa.Column('certification_scheme_id', sa.Integer(), nullable=False),
    sa.Column('requirement_type', sa.String(length=100), nullable=True),
    sa.Column('mandatory', sa.String(length=50), nullable=True),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['certification_scheme_id'], ['certification_schemes.id'], ),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('standard_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('standard_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('version_type', sa.String(length=50), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('document_url', sa.Text(), nullable=True),
    sa.Column('supersedes_version_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], ),
    sa.ForeignKeyConstraint(['supersedes_version_id'], ['standard_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chunk_embeddings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chunk_id', sa.String(length=36), nullable=False),
    sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chunk_embeddings', schema=None) as batch_op:
        batch_op.create_index('hnsw_chunk_vector_idx', ['vector'], unique=False, postgresql_using='hnsw', postgresql_ops={'vector': 'vector_cosine_ops'})

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chunk_embeddings', schema=None) as batch_op:
        batch_op.drop_index('hnsw_chunk_vector_idx', postgresql_using='hnsw', postgresql_ops={'vector': 'vector_cosine_ops'})

    op.drop_table('chunk_embeddings')
    op.drop_table('standard_versions')
    op.drop_table('standard_certification')
    op.drop_table('standard_amendments')
    op.drop_table('product_standard_mapping')
    op.drop_table('document_chunks')
    op.drop_table('uploads')
    op.drop_table('standards')
    op.drop_table('services')
    op.drop_table('products')
    op.drop_table('laboratories')
    op.drop_table('certification_schemes')
    # ### end Alembic commands ###
